language: android
script: "./gradlew build"
android:
    components:
        - build-tools-21.1.2
        - android-21

        - extra-android-m2repository
        - extra-android-support
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-google-play_apk_expansion
        - extra-google-play_billing
        - extra-google-play_licensing
        - extra-google-simulators
        - extra-google-webdriver
